### ISSUE TITLE
(logging): text logs when JSON format is enabled

### ISSUE THREAD

**Issue by plafer** [aws-greengrass/aws-greengrass-cli#123] opened 2021-05-19 20:56 UTC
**Describe the bug**
My Nucleus is configured to log in JSON. However, the first 4 lines logged upon booting greengrass core are in text, which makes `greengrass-cli logs get -lf /greengrass/v2/logs/greengrass.log` fail.

**To Reproduce**
1. Remove `/greengrass/v2/logs/greengrass.log`
2. Restart the greengrass service (I rebooted the machine)
3. `# less /greengrass/v2/logs/greengrass.log`

Notice that the first four lines are text. In my case (I included the first json-formatted line as well):

>2021-05-19T20:45:08.193Z [INFO] (main) com.aws.greengrass.util.platforms.Platform: Getting platform instance com.aws.greengrass.util.platforms.unix.UnixPlatform.. {}
2021-05-19T20:45:08.294Z [INFO] (main) com.aws.greengrass.lifecyclemanager.Kernel: No ongoing deployment detected. Proceed as default. {}
2021-05-19T20:45:08.628Z [INFO] (main) com.aws.greengrass.config.Configuration: config-loading. Read configuration from a file path. {path=/greengrass/v2/config/config.tlog}
2021-05-19T20:45:09.840Z [INFO] (main) com.aws.greengrass.lifecyclemanager.Kernel: effective-config-dump-complete. {file=/greengrass/v2/config/effectiveConfig.yaml}
{"thread":"main","level":"INFO","eventType":null,"message":"Copy Nucleus artifacts to component store","contexts":{"destination":"/greengrass/v2/packages/artifacts-unarchived/aws.greengrass.Nucleus/2.1.0/aws.greengrass.nucleus","source":"/home/muffin/GreengrassCore"},"loggerName":"com.aws.greengrass.deployment.DeviceConfiguration","timestamp":1621457110186,"cause":null}

**Expected behavior**
I expect these four lines to be encoded in JSON.

**Actual behavior**
The four lines are encoded in text.

**Environment**
 - OS: Ubuntu 18.04 on Jetson Nano
 - JDK version: openjdk 11.0.11 2021-04-20
 - Nucleus version: 2.1.0
 - CLI version: 2.1.0

**Comment by MikeDombo** [comment] 2021-05-19 20:59
They won't be in JSON because those lines are logged before the Nucleus has even read its configuration, so it doesn't know that it should be using JSON at that point. The CLI should be skipping those lines and continuing on to everything else.

**Comment by MikeDombo** [comment] 2021-05-19 21:01
You can force it by deploying updated JVM options to the Nucleus components which includes `-Dlog.format=JSON`. This will then be inserted as a Java system property which the logger will then read in; thus setting the format before Nucleus has read in the full configuration.

**Comment by MikeDombo** [comment] 2021-05-19 21:06
Closing as unfortunate, but expected behavior. The CLI will warn that it couldn't parse them, but it should keep on going to show the rest of everything else.

**Closed** 2021-05-20 00:36 UTC
Labels: bug
