### ISSUE TITLE
(logs get): --log-dir option doesn't show all logs in directory

### ISSUE THREAD

**Issue by plafer** [aws-greengrass/aws-greengrass-cli#122] opened 2021-05-15 19:14 UTC
**Note:** All commands shown below are run as root.

**Describe the bug**
`greengrass-cli logs get --logs-dir /greengrass/v2/logs` doesn't show all logs in the directory.

**To Reproduce**
1. Deploy something on greengrass device such that logs are generated. Confirm that `greengrass-cli logs get -lf /greengrass/v2/logs/greengrass.log` shows the latest log to be at the current time `t1`.
2. Revise the deployment with another component which will also generate some logs. Confirm that `greengrass-cli logs get -lf /greengrass/v2/logs/greengrass.log` shows the latest log to be at the current time `t2`.
3. `greengrass-cli logs get --logs-dir /greengrass/v2/logs` does not show the latest log entry, as shown by `greengrass-cli logs get --logs-dir /greengrass/v2/logs`.

**Expected behavior**
I would expect `greengrass-cli logs get --logs-dir /greengrass/v2/logs` to show a superset of `greengrass-cli logs get -lf /greengrass/v2/logs/greengrass.log`, since the file `/greengrass/v2/logs/greengrass.log` is in the `/greengrass/v2/logs` directory, and `logs-dir` is documented as searching the whole directory for logs.

**Actual behavior**
 `greengrass-cli logs get --logs-dir /greengrass/v2/logs` doesn't show the latest log messages. The last returned entry is from a previous deployment (a couple of hours earlier in my case).

**Environment**
 - OS: Ubuntu 18.04 on Jetson Nano
 - JDK version: 11.0.11 2021-04-20 (taken from `java --version`)
 - Nucleus version: 2.1.0
 - CLI version: 2.1.0

**Additional context**
I would expect `--log-dir` to look at *all* log entries present in *all* files in the specified directory. I usually add filters to this command to look for something specific. Because of this (alleged) bug, I no longer know how to look at all log messages in one command.

**Comment by MikeDombo** [comment] 2021-05-15 19:25
Hello Phillipe,
Can you confirm that the log files which you are trying to read are JSON formatted? The log reader will only work for JSON logs and not plain-text.

**Comment by plafer** [comment] 2021-05-16 13:09
I confirm. Here is the latest log message generated in `/greengrass/v2/logs/greengrass.log`:

> {"thread":"Thread-10","level":"INFO","eventType":null,"message":"Sending connect response for greengrass-cli-user-0","contexts":{},"loggerName":"software.amazon.awssdk.eventstreamrpc.ServiceOperationMappingContinuationHandler","timestamp":1621170371968,"cause":null}


Here is my Nucleus config:

>---
componentType: "NUCLEUS"
configuration:
  awsRegion: "us-east-1"
  componentStoreMaxSizeBytes: "10000000000"
  deploymentPollingFrequency: "15"
  deploymentPollingFrequencySeconds: 15
  envStage: "prod"
  fleetStatus:
    periodicStatusPublishIntervalSeconds: 86400
  greengrassDataPlanePort: "8443"
  iotCredEndpoint: "c1kj80aqxwkeoh.credentials.iot.us-east-1.amazonaws.com"
  iotDataEndpoint: "a2kf5unhpbglxb-ats.iot.us-east-1.amazonaws.com"
  iotRoleAlias: "MyGreengrassCoreTokenExchangeRoleAlias"
  jvmOptions: "-Dlog.store=FILE"
  logging:
    format: "JSON"
  mqtt:
    spooler: {}
  networkProxy:
    proxy: {}
  platformOverride: {}
  runWithDefault:
    posixShell: "sh"
    posixUser: "ggc_user:ggc_group"
  telemetry: {}
dependencies: []
lifecycle:
  bootstrap:
    requiresPrivilege: "true"
    script: "\nset -eu\nKERNEL_ROOT=\"/greengrass/v2\"\nUNPACK_DIR=\"/greengrass/v2/packages/artifacts-unarchived/aws.greengrass.Nucleus/2.1.0/aws.greengrass.nucleus\"\
      \nrm -r \"$KERNEL_ROOT\"/alts/current/*\necho \"-Dlog.store=FILE\" > \"$KERNEL_ROOT/alts/current/launch.params\"\
      \nln -sf \"$UNPACK_DIR\" \"$KERNEL_ROOT/alts/current/distro\"\nexit 100"
version: "2.1.0"

**Comment by MikeDombo** [comment] 2022-09-27 12:14
@plafer,

We are unable to reproduce this issue. Can you confirm that this is still a problem?

If it is not a problem, or if we do not receive a reply, we will close this issue.

**Closed** 2022-10-20 14:16 UTC
Labels: bug, closing-soon
